### ISSUE TITLE
Help！！！

### ISSUE THREAD

**Issue by tms988** [michaelyinopen/job-shop-scheduler#4]
Dear coder,
I downloaded your code, but I don't know how to run it. Can you help me? If you can, can you update the details in ReadMe.

**Comment by michaelyinopen** [comment]
Hi @tms988 ,
Apologies that the code could not run. I have included the missing dependency and updated Readme.
Cheers

**Comment by tms988** [comment]
> Hi @tms988 ,
> Apologies that the code could not run. I have included the missing dependency and updated Readme.
> Cheers

I got your update code, because the network is too bad, did not reply in time, thank you so much
